version: "3.5"

# you can disable any of services by using comment

services:
  pdfMaker:
    build:
      context: .
      dockerfile: submodules/latex/Dockerfile
    image:
      amd64: marmot0814/latex
      default: null
    container_name: pdfMaker
    command: ["sleep","infinity"]
    restart: on-failure
    volumes:
      - ".:/storage"
