name: Compile latex and release pdf

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [ master ]

jobs: 
  release-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build stack and generate pdf
        run: make build && make pdf
      - name: Generate release tag
        id: tag
        run: echo "release_tag=$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
      - name: Release pdf
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          target_commitish: ${{ github.sha }}
          files: |
            problem.pdf
