name: Preview pdf

permissions:
  pull-requests: write
  contents: write

on:
  pull_request:
    branches: [ master ]

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the environment
        run: make build
      - name: Generate pdf
        run: make pdf
      - name: Generate release
        run: bash scripts/release.sh
      - name: Upload Artifact
        id: upload
        uses: actions/upload-artifact@v3.1.2
        with:
          name: problem
          path: release/*.pdf
          if-no-files-found: error
